version: '3.9'

services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

  rts-server:
    image: localhost:5000/rts-server:latest
    container_name: rts-server
    ports:
      - "8080:8080"
    depends_on:
      - registry
    restart: always

volumes:
  registry_data:
