version: '3.8'

services:
  rts-server:
    image: yourusername/rts-server:latest
    container_name: rts-server-container
    ports:
      - "8080:8080" # Map the necessary ports
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
